# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='products',
        ),
    ]
