# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('no_of_stock', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('categories', models.ManyToManyField(to='products.Category')),
            ],
        ),
    ]
